### ISSUE TITLE
请问有参考的论文吗？

### ISSUE THREAD

**Issue by LightersWang** [zc402/ChineseTrafficPolicePose#1]
如果没有参考的论文，那请问这个项目的算法流程大致是什么呢？这样我看代码能快一点，谢谢了！

**Comment by qq491577803** [comment]
亲，你的手势训练集在哪下载呀，求连接，小白想跟大佬学学

**Comment by zc402** [comment]
骨骼训练集是 https://www.challenger.ai/datasets/keypoint
手势训练集我自己录的，30分钟就够。等文章发了数据集公开

**Comment by Xuxiangqi123456** [comment]
请问你的论文发表了吗?

**Comment by zc402** [comment]
快发表了。。。。这个东西真的是耗费时间。。。

**Comment by miaowu16** [comment]
数据集放出来了，是论文是中了吗？论文有arxiv下载链接吗

**Comment by zc402** [comment]
论文还在审稿中呐。。应Reviewer要求公开数据集。没放arxiv，我不知道期刊允许不允许这么做

**Comment by zc402** [comment]
论文preprint发表了，neurocomputing，学校买的数据库应该都有它的。地址在readme。一年半啊时间好长
