### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by wangjiaxing72** [zc402/ChineseTrafficPolicePose#2]
请问这个程序怎么运行？有详细的步骤吗？

**Comment by zc402** [comment]
照readme把模型放到相应的文件夹下，然后命令行输入 python3 rnn_webcam.py。cuda，tensorflow-gpu 和python缺少的包需要自行安装，提示缺那个就装哪个就行。opencv也可用pip3装。

**Comment by leoncesc** [comment]
PAF网络和rnn网络都需要先训练吗？有没有训练好的模型，我可以用来跑个demo看看效果？如果有已经训练好的模型，怎么跑rnn网络测试我自己录的视频？rnn网络输入数据具体格式或者预处理能介绍一下吗？
